apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: walt-id
  namespace: argocd
  labels:
    purpose: marketplace-iam
spec:
  destination:
    namespace: marketplace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: azure/marketplace/iam/vcwaltid
    repoURL: https://github.com/in2workspace/dome-gitops-aks
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true