apiVersion: v1
kind: Secret
metadata:
  name: access-node-secret
  namespace: marketplace
data:
  desmos-db-password: TXlQYXNzd29yZC4tMTIzNDU2
  desmos-private-key: MHg0M2IyN2ZlZjI0Y2ZlOGEwYjc5N2VkOGEzNmRlMjg4NGY5OTYzYzBjMmEwZGE2NDBlM2VjN2FkNmNkMGM0OTNk
  dlt-private-key: MHg0M2IyN2ZlZjI0Y2ZlOGEwYjc5N2VkOGEzNmRlMjg4NGY5OTYzYzBjMmEwZGE2NDBlM2VjN2FkNmNkMGM0OTNk
  scorpio-db-password: TXlQYXNzd29yZC4tMTIzNDU2