apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.apps_Deployment: |
    jsonPointers:
    - /spec/replicas
  url: https://dome-argocd.dev.in2.es
  admin.enabled: "false"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23li4yWEQViQYejE6h
          clientSecret: 48e2f64bb32dc03aa306f66c0c12bfe2ac0c1893
          orgs:
          - name: DOME-Marketplace
          - name: in2workspace