apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    purpose: infra
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: azure/external-dns
    repoURL: https://github.com/in2workspace/dome-gitops-aks
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true