apiVersion: v1
kind: Secret
metadata:
  name: bae-secret
  namespace: marketplace
data:
  dbPassword: TXlQYXNzd29yZC4tMTIzNDU2
  idmPassword: TXlQYXNzd29yZC4tMTIzNDU2
  oauthClientSecret: TXlQYXNzd29yZC4tMTIzNDU2
  paypalClientSecret: TXlQYXNzd29yZC4tMTIzNDU2
  pluginsIdmPassword: TXlQYXNzd29yZC4tMTIzNDU2
  privateKey: 0x43b27fef24cfe8a0b797ed8a36de2884f9963c0c2a0da640e3ec7ad6cd0c493d
  smtpPassword: TXlQYXNzd29yZC4tMTIzNDU2
