dsba-pdp:
  db: 
    enabled: false
    migrate:
      enabled: false
  deployment:
    image:  
      pullPolicy: Always
      repository: quay.io/fiware/dsba-pdp 
      tag: 1.2.0
    logLevel: DEBUG
    ishare:
      existingSecret: walt-id-vcwaltid-tls-sec

      clientId: did:web:dome-marketplace.dev.in2.es
      trustedFingerprints:
        - D2F62092F982CF783D4632BD86FA86C3FBFDB2D8C8A58BC6809163FCF5CD030B

      ar:
        id: "did:web:dome-marketplace.dev.in2.es"
        delegationPath: "/ar/delegation"
        tokenPath: "/oauth2/token"
        url: "https://keyrock-dome.dev.in2.es"

      trustAnchor:
        id: "EU.EORI.FIWARESATELLITE"
        tokenPath: "/token"
        trustedListPath: "/trusted_list"
        url: "https://tir-dome.dev.in2.es"
        
    trustedVerifiers:
      - https://verifier-dome.dev.in2.es/.well-known/jwks

    providerId: "did:web:dome-marketplace.dev.in2.es"
    
  additionalEnvVars:
    - name: ISHARE_CERTIFICATE_PATH
      value: /iShare/tls.crt
    - name: ISHARE_KEY_PATH
      value: /iShare/tls.key