---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-access-key
  namespace: infra
spec:
  encryptedData:
    credentials: AgBsRANdzpNefM6AvN/fxq8EHmQP13G/ubdPqms7KiJNOr5YJ1VUTGZQEqDH0JYLAPbKPH0fqjh+5MWavW3xxEwVMMah4SBZE/hR4NTo+u7sVjsaRAkFsGGKLio9Nud9bNGtpDJFEtSUx7DQzA2VPqGknZ1+89jpS9wEE+GtvJaAuwyqQNR9fJvxVawigWih6cl5wF1/aAyc339GVSY5xQuRlOEna6/6URMdAZWejZFLBPNaSBcf3qf4MnMwgV3FaK/PF5l7NDsqHkvuJEb8zywePMHmGle0w4iGBks2gVAEJ36JuxLmyR5VVUB9uzP2UfzYZoVuM17WariXCjCq1iSgbqVlTn/jdNxH2su7jbXiSsksKEVgw6LqOdhjTsL7iOPeeSoiExluvstSqPrTpdR8gJ82PhEYceqeE3eVbNTfygK63Kkl/B1NK5xrRJMWLt5De7I6Vgj3fi1MBht4czb/DKZqBa4rThmGYe+8u56833e49Fp8d71RFVcyuPM5oHqYrTD3FBeO2zP4YRF9r517ibA0u9Vle6sRXtZet/hGe+m2p+SH4OWNMjWDg0rLYq7jwWWE5iE18qddSP6tyEggFOlXOssqitbeDPsWQmcYo5Yf6Ims5HFOKODQ6sDFiEBrZdeHaOXA3s0M6LcoUg90P37q/rVapK/kFe47RxiqJcnylomwFn/kFzPjJcwag4E89USb/TVpSqPS8F+2X7FnkbOInJGJcIotrtY1caw8pXafJBJlNaix6SSdflr+I9tPcX6ox5qEczn8FWBWMx6GrshqNGnm5fwkDcM1IlxIOJQXMqOTGC15aWRKMwgSDGdf4qolaTK0gc7fmrJgvg/MRcwiCwjjCQzeuqgfgZqZiDQkPvy6kxuR+4Jh8Nmo4fi4ffO+uefMcXvlK5V2AbCz61eRQUTh1fNiIqqtzVlSOlM9UsZZ5X1PmMlwx+cB9SGWf6+7XTO+oEMJD1B33+cxpug+YdWAzwvNtmhyvGCg8qG+CxypCFzpnLZtS0BvH3zIZ9wawbZZJPGLMF9hj3u65BnuODN2NeLLa3hBhZ6KmFb49UI=
  template:
    metadata:
      creationTimestamp: null
      name: azure-access-key
      namespace: infra
